name: ESLint

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    eslint:
        name: Run eslint scanning
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v6
              with:
                  node-version-file: "package.json"

            - name: Fetch Dependencies
              run: npm install

            - name: Run ESLint
              env:
                  SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
              run: npm run eslint .
                  --format @microsoft/eslint-formatter-sarif
                  --output-file results.sarif
              continue-on-error: true

            - name: Upload Results
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: results.sarif
                  wait-for-processing: true
